### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by duckyb** [ashwinbalachandran/ergogenstuff#1]
I'm making this issue to report everything I see that you should fix about the design and give some tips on how to do it.

For reference, this is my work environment:
![image](https://user-images.githubusercontent.com/27895007/167612323-ab47fcc8-2f0b-459d-a46a-992bf85c2d74.png)

## Design Rule Checker

The first step is to run the DRC tool and see what issues appear. These things must all be fixed or at least adressed.
If you want to move the view on the problem you just need to click on the DRC issue and it will move your view inside the PCB editor.

### Tracks with unconnected ends

![image](https://user-images.githubusercontent.com/27895007/167613137-c04b65b5-4b64-4cd9-a504-9a06a433721b.png)

In this case, there is an overlap of some tracks that you need to fix. Just select and delete the extra track and re-route that bit correctly.

### Edge clearance violation

![image](https://user-images.githubusercontent.com/27895007/167613375-f0a18f5f-8f1a-497a-8640-688414cafa45.png)

Here you have an extra circle inside your edge cuts layer. This circle overlaps a trace (the green one) so kicad complains.
I believe this circle is a mistake, in this case you should delete it.

### Drilled holes too close together

![image](https://user-images.githubusercontent.com/27895007/167613750-3ae06294-f062-4a11-92e3-604ea40ced31.png)

This is a problem in the setup of Kicad, usually the factories are able to create overlapping drill holes so you can remove this limitation in the PCB editor settings.

![image](https://user-images.githubusercontent.com/27895007/167614085-3f2271f6-7e4b-4d74-8f63-79b135b4909c.png)

Just set to zero.

### Malformed outline

![image](https://user-images.githubusercontent.com/27895007/167614250-6538d47e-bd13-41c4-be4f-ca2072a49e42.png)

Pretty self-explanatory, why is there this circle in the board edge? I think you should delete it.

***

Here is how the board looks with zero errors:

![image](https://user-images.githubusercontent.com/27895007/167615290-f859cca4-1d07-417c-b18e-9d081c2718de.png)

**Comment by ashwinbalachandran** [comment]
Just fixed all the issues: [Adding fixed pcb & gerbers](https://github.com/ashwinbalachandran/ergogenstuff/commit/bd4cb90461a426ba8afc91ac57d5b5cd48f2a05a)

Thanks a lot @duckyb !

**Comment by duckyb** [comment]
@ashwinbalachandran ok. I'll have another look. Now that the board is possible to make, we can look if it makes sense from a user point of view
