### ISSUE TITLE
Design review #2

### ISSUE THREAD

**Issue by duckyb** [ashwinbalachandran/ergogenstuff#2]
Great, now the PCB is functional. Let's see if there are other issues.

## Switch pads

![image](https://user-images.githubusercontent.com/27895007/168176716-09449930-4327-46a1-a0b0-ec7d3e9a8b37.png)

First tip I can give you is, think about what a switch does, it simply connects two points when pressed.
It does not matter which pad is what, you will still make the same connection.

What this means is that you can reverse the order of pad 1 and 2 of the switches every time you want.

You can use this to your advantage, by bringing all of the same pads close together, to make routing easier.

In your PCB you have the pins on opposite sides, in this footprint you see that all of the same pins are on the same side. (left/right)

[MX_solder&socket_reversible.zip](https://github.com/ashwinbalachandran/ergogenstuff/files/8682876/MX_solder.socket_reversible.zip)

## Ground plane

You can also add a fill zone for GND. This way you don't need to manually connect anything to it.

![image](https://user-images.githubusercontent.com/27895007/168177392-4526d9b8-592d-496b-b2c9-109a7c898c57.png)

For example you can add a copper zone that covers the entirety of the PCB with these settings. After you fill the zone ("B" key) every GND pad will be connected.

## Switch spacing

![image](https://user-images.githubusercontent.com/27895007/168177554-f82ea5d0-3925-42a3-9ed8-e376be03efe0.png)

You are not respecting the MX switch courtyards. The courtyard is the space you need to leave for the physical component that will go on the PCB.

For MX switches you need a 14x14mm spacing. If you don't use this the keycaps will hit each other. The spacing you are using at the moment is choc spacing, only suitable for choc switches.

![image](https://user-images.githubusercontent.com/27895007/168177747-4ba98257-950b-42be-9c69-5a703319edeb.png)

You also have it on the thumb cluster, you need to separate the keys more.

**Comment by ashwinbalachandran** [comment]
Hi @duckyb, so I managed to fix the first 2 issues, but I guess I should've done the last one first. When you mentioned that MX is supposed to be 14x14mm spacing what exactly does that mean?

is it center to center distance, if yes is there a way to measure or is the Kicad ruler approximate measurement enough?

**Comment by duckyb** [comment]
If you edit a footprint value (select and press E) you will see x and y values.

Also you can see the square on the footprint. That's 14x14mm.

If the squares overlap then it's too close.

**Comment by duckyb** [comment]
@ashwinbalachandran sorry I got confused and told you the wrong numbers.
```
standard MX cutout - 14×14mm (size of the switch)
distance between switches (center to center) - 19.05mm (both vertically and horizontally)
```

You need 19.05 between keys in order to avoid keycaps touching each other.
The suggestion to use the footprint outline as reference is still valid.

Try using a custom kicad grid size of `0.79375mm (19.05/24)` to place the switches, as suggested [here](https://wiki.ai03.com/books/pcb-design/page/pcb-guide-part-5---creating-the-pcb)

**Comment by ashwinbalachandran** [comment]
Ohh ok that makes sense, i just measured one of my keycaps and realized it might be around 18/19mm just didnt know what exactly that measurement was.

I'll try changing that, thanks

**Comment by ashwinbalachandran** [comment]
@duckyb I don't know if you can see my PR https://github.com/ashwinbalachandran/ergogenstuff/pull/3 but i basically did changes 2 & 3 also did 1 but it was so tedious to change each footprint. I used ergogen to generate the layout and bindings I think so those MX switches have the Pins and GND on opposite sides and each footprint was unique footprint.

**Comment by duckyb** [comment]
@ashwinbalachandran looks like a fully functional PCB now.

Two things I notice are:

## 1)
![image](https://user-images.githubusercontent.com/27895007/169646552-cbc420a7-32a3-4816-98bd-69fa6255d91b.png)

JLC might ask you to increase the distance to at least 4 mm to avoid unwanted damage to the PCB in production. But what's the point of having a hole under the TRRS port anyway?

## 2)
![image](https://user-images.githubusercontent.com/27895007/169646710-e46d1afc-1b9f-4cc3-80fd-6aa9f4870e70.png)

This isn't really how I would rearrange the footprint but if you like it this way it works fine 😄

**Comment by ashwinbalachandran** [comment]
Hi @duckyb thanks for all the help. Just wanted to clarify, I had originally changed the footprint but after I fixed the switch spacing it all got deleted since I manually edited every single footprint. After that I was just lazy to do it all again, I also moved the trrs & removed that circle under it.
